### ISSUE TITLE
Examples and Example in ParameterObj

### ISSUE THREAD

**Issue by undera** [chanced/openapi#4]
Hello,

Thanks for your nice library, it's a rare project that supports OAS 3.1

I have a question about examples fields in parameters. In OAS Spec I see that there can be 2 options to specify examples (https://spec.openapis.org/oas/v3.1.0#fixed-fields-9): `example` and `examples`, mutually exclusive.

In the `ParameterObj` I only see the `Examples` field. Trying to load the following document with library gives no access to `example` value:

```json5
{
  "openapi": "3.1.0",
  "info": {
    "title": "",
    "version": ""
  },
  "paths": {
    "/catalogue/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "schema": {
            "type": "string"
          },
          "example": "some-uuid-maybe"
        }
      ]
    }
  }
}
```

Is there a plan to support the `example`, as defined in OAS 3.1 specification?

**Comment by chanced** [comment]
Ah, thank you for pointing out my oversight! I will add that and push up a patch either today or tomorrow.

Btw, I'm working on improving the package considerably. I realize it is a bit of a hassle to work with at the moment but #3 should hopefully make it a bit easier, at least from parsing existing specifications.

I'm almost done with a json pointer package to support it and then it shouldn't be much longer after that.

Thanks again for the heads up!

**Comment by undera** [comment]
Sounds good. There's no extreme urgency for me to fix this, take your time.

As a general feedback about library usage, I can share that my usecase is creating/altering OAS programmatically, so in certain places where `$ref` can be, I have to use code like this to handle the structure:
```golang
	var response openapi.Response
	response, found := opObj.Responses[statusStr]
	if !found {
		opObj.Responses[statusStr] = &openapi.ResponseObj{Content: map[string]*openapi.MediaType{}}
		response = opObj.Responses[statusStr]
	}

	var resResponse *openapi.ResponseObj
	switch response.ResponseKind() {
	case openapi.ResponseKindRef:
		return nil, errors.New("response reference is not supported at the moment")
	case openapi.ResponseKindObj:
		resResponse = response.(*openapi.ResponseObj)
	}
        return resResponse
```
which I'm not sure the way you've envisioned it.

**Comment by chanced** [comment]
That is going to be changing. That was how I initially envisioned it but its sort of a pain to have to perform those switches everywhere. [The individual Kinds are being abandoned for a single Kind](https://github.com/chanced/openapi/blob/feat/add-load/kind.go).

The new API is going to incorporate a `Load` function which will resolve all references and provide `Resolved{Type}` structs, removing the need to perform those checks. 

This would be helpful when simply parsing a specification but the downside is I am not 100% on how to Marshal it back to JSON in the event of modifying. Ideally, everything feasible would be moved to `Components`. The challenge with that is three fold:
1. Naming within the components. Clearly solvable, I'm just not sure the best way to go about it at the moment.
2. Schemas are a challenge. Since schemas are a multi-dimensional tree, they can't (or at least shouldn't) be flattened out. Arguably, top level schemas could be moved, but I don't know what do about schemas that reference other schemas.
3. Modifying resolved objects may not be user friendly.

It may make sense to use the current approach (with the new Kind) when modifying and only using `Load` when needing to simply parse. I don't know.

**Comment by chanced** [comment]
This has been hackishly solved for now. `Example` was added but its just a `json.RawMessage` for now. I don't handle the mutual exclusivity or the overriding logic.

**Comment by undera** [comment]
Thanks you very much!

**Comment by chanced** [comment]
@undera finally finished up the json pointer package which may be useful to you: https://github.com/chanced/jsonpointer

it should be a few days before I'm done with the refactor. Cheers.
